### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tasoskakour** [tasoskakour/react-use-oauth2#1]
- [x] Initial version of the library
- [x] Setup examples for code and token grant
- [x] Add UI custom component for Popup
- [x] Handle popup forcefully closing before completing auth
- [x] Check hook state persistence
- [x] Write a nice  README.md
- [x] Write some tests
- [x] Check why rollup doesn't read env vars from .envrc (although it does read them from terminal)
